### ISSUE TITLE
RuntimeError: status == CUBLAS_STATUS_SUCCESS. 13 vs 0.

### ISSUE THREAD

**Issue by MarcusNerva** [LuoweiZhou/detectron-vlp#10]
Hello, Thank you for your feature extraction code!
However, I run into a 'RuntimeError'.
Enviroment:
the same as [gvd_py2.7](https://github.com/facebookresearch/grounded-video-description/blob/master/cfgs/conda_env_gvd.yml)
OS: Ubuntu 20.04
Do you know what happened?

> [I net_async_base.h:205] Using specified CPU pool size: 4; device id: -1
[I net_async_base.h:210] Created new CPU pool, size: 4; device id: -1
[E net_async_base.cc:377] [enforce fail at math_gpu.cu:569] status == CUBLAS_STATUS_SUCCESS. 13 vs 0. Error at: /opt/conda/conda-bld/pytorch_1556653000816/work/caffe2/utils/math_gpu.cu:569: CUBLAS_STATUS_EXECUTION_FAILED
Error from operator: 
input: "gpu_0/fc7" input: "gpu_0/bbox_pred_w" input: "gpu_0/bbox_pred_b" output: "gpu_0/bbox_pred" name: "" type: "FC" arg { name: "use_cudnn" i: 1 } arg { name: "cudnn_exhaustive_search" i: 0 } arg { name: "order" s: "NCHW" } device_option { device_type: 1 device_id: 0 }frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x59 (0x7f67576f7409 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: void caffe2::math::Gemm<float, caffe2::CUDAContext, caffe2::DefaultEngine>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*, caffe2::CUDAContext*, caffe2::TensorProto_DataType) + 0x6da (0x7f675a65399a in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2_gpu.so)
frame #2: <unknown function> + 0x14e3730 (0x7f6759286730 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2_gpu.so)
frame #3: <unknown function> + 0x14d8e88 (0x7f675927be88 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2_gpu.so)
frame #4: <unknown function> + 0x13cb0b5 (0x7f675916e0b5 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2_gpu.so)
frame #5: caffe2::AsyncNetBase::run(int, int) + 0x144 (0x7f677bc7cb94 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #6: <unknown function> + 0x168f009 (0x7f677bc83009 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #7: c10::ThreadPool::main_loop(unsigned long) + 0x2a3 (0x7f67576f12f3 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #8: <unknown function> + 0xb8678 (0x7f67929ce678 in /home/marcusnerva/anaconda3/envs/gvd_pt1_1/bin/../lib/libstdc++.so.6)
frame #9: <unknown function> + 0x9609 (0x7f6798fd0609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #10: clone + 0x43 (0x7f6798d9d293 in /lib/x86_64-linux-gnu/libc.so.6)
,  op FC
[E net_async_base.cc:129] Rethrowing exception from the run of 'generalized_rcnn'

**Comment by MarcusNerva** [comment]
Problem solved!
For the procedure of setting up and configured environment and the problem cause by python version, you can refer to #5 

To solve the problem I mentioned above, you have to modify the source code:
change
https://github.com/LuoweiZhou/detectron-vlp/blob/aa22e50935b463e52d69bd790b2d8351bc26014e/lib/core/test.py#L158
to:
`
try:
        workspace.RunNet(model.net.Proto().name)
except Exception:
        print('')
` 
Then you can extract features by using detectron-vlp.

**Comment by youreternity1997** [comment]
I have the same problem. Because I do not have enough RAM on my GPU to run it, I choose a bigger RAM GPU to solve the problem successfully.
